module.exports = {
    chainID: 'arkh',
    lcd: 'https://arkh.api.m.anode.team',
    gasAdjustment: 1.75,
    gasPrices: {arkh: 0.025},
    prefix: 'arkh',
    coinType: '118',
    baseAsset: 'arkh',
    name: 'Arkhadian',
    chainRegistryName: 'arkh',
    disabledModules: ['swap'],
    icon: process.env.CF_PAGES_URL + '/img/chains/arkh.svg',
    gitRepo: 'https://github.com/vincadian/arkh-blockchain',
    autoCompound: {
        enabled: true,
        minRewards: 1000000
    },
    channels: {
        'akashnet-2': 'channel-4',
        'axelar-dojo-1': 'channel-18',
        'bitcanna-1': 'channel-26',
        'bitsong-2b': 'channel-15',
        'cerberus-chain-1': 'channel-17',
        'cheqd-mainnet-1': 'channel-24',
        'comdex-1': 'channel-3',
        'core-1': 'channel-5',
        'crescent-1': 'channel-16',
        'desmos-mainnet': 'channel-27',
        'dig-1': 'channel-28',
        'evmos_9001-2': 'channel-14',
        'gravity-bridge-3': 'channel-13',
        'impacthub-3': 'channel-29',
        'injective-1': 'channel-11',
        'iov-mainnet-ibc': 'channel-25',
        'juno-1': 'channel-1',
        'kaiyo-1': 'channel-12',
        'kichain-2': 'channel-22',
        'likecoin-mainnet-2': 'channel-21',
        'mantle-1': 'channel-20',
        'omniflixhub-1': 'channel-23',
        'osmosis-1': 'channel-0',
        'phoenix-1': 'channel-8',
        'regen-1': 'channel-6',
        'secret-4': 'channel-10',
        'sentinelhub-2': 'channel-7',
        'sommelier-3': 'channel-19',
        'stargaze-1': 'channel-2',
        'umee-1': 'channel-9',
    },
    explorer: {
        address: 'https://main.anode.team/arkh/account/{}',
        tx: 'https://main.anode.team/arkh/tx/{}',
        validator: 'https://main.anode.team/arkh/staking/{}',
        block: 'https://main.anode.team/arkh/blocks/{}',
    },
    tokens: [
        {
            token: 'arkh',
            symbol: 'ARKH',
            name: 'Arkhadian',
            icon: process.env.CF_PAGES_URL + '/img/coins/arkh.svg',
            decimals: 6,
        },
    ],
}
