module.exports = {
    chainID: 'comdex-1',
    lcd: 'https://comdex-rest.publicnode.com',
    rpc: 'https://comdex-rpc.publicnode.com',
    gasAdjustment: 1.75,
    gasPrices: {ucmdx: 0.025},
    prefix: 'comdex',
    coinType: '118',
    baseAsset: 'ucmdx',
    name: 'Comdex',
    chainRegistryName: 'comdex',
    disabledModules: ['swap'],
    icon: process.env.CF_PAGES_URL + '/img/chains/Comdex.svg',
    gitRepo: 'https://github.com/comdex-official/comdex',
    autoCompound: {
        enabled: false,
        minRewards: 100000
    },
    channels: {
        'phoenix-1': 'channel-51',
        'axelar-dojo-1': 'channel-34',
        'crescent-1': 'channel-26',
        'juno-1': 'channel-18',
        'migaloo-1': 'channel-63',
        'osmosis-1': 'channel-1',
        'stride-1': 'channel-45',
    },
    explorer: {
      address: 'https://finder.hexxagon.io/comdex-1/address/{}',
      tx: 'https://finder.hexxagon.io/comdex-1/tx/{}',
      validator: 'https://finder.hexxagon.io/comdex-1/validator/{}',
      block: 'https://finder.hexxagon.io/comdex-1/block/{}',
    },
    tokens: [
        {
            token: 'ucmdx',
            symbol: 'CMDX',
            name: 'Comdex',
            icon: process.env.CF_PAGES_URL + '/img/coins/Comdex.svg',
            decimals: 6,
            coinGeckoID: 'comdex',
        },
        {
            token: 'ucmst',
            symbol: 'CMST',
            name: 'Composite',
            icon: process.env.CF_PAGES_URL + '/img/coins/CMST.svg',
            decimals: 6,
        },
        {
            token: 'uharbor',
            symbol: 'HARBOR',
            name: 'Harbor',
            icon: process.env.CF_PAGES_URL + '/img/coins/Harbor.svg',
            decimals: 6,
        },
    ],
}
