module.exports = {
    chainID: 'cosmoshub-4',
    lcd: 'https://cosmos-rest.publicnode.com',
    gasAdjustment: 1.75,
    gasPrices: {uatom: 0.025},
    prefix: 'cosmos',
    coinType: '118',
    baseAsset: 'uatom',
    name: 'Cosmos',
    chainRegistryName: 'cosmoshub',
    disabledModules: ['swap'],
    icon: process.env.CF_PAGES_URL + '/img/chains/Cosmos.svg',
    gitRepo: 'https://github.com/cosmos/gaia.git',
    autoCompound: {
        enabled: true,
        minRewards: 200000
    },
    ibc: {
        fromTerra: 'channel-2',
        toTerra: 'channel-219',
    },
    channels: {
        'columbus-5': 'channel-219',
        'phoenix-1': 'channel-339',
        'axelar-dojo-1': 'channel-293',
        'carbon-1': 'channel-342',
        'akashnet-2': 'channel-184',
        'crescent-1': 'channel-326',
        'juno-1': 'channel-207',
        'kaiyo-1': 'channel-343',
        'osmosis-1': 'channel-141',
        'stride-1': 'channel-391',
        'pacific-1': 'channel-584',
        'archway-1': 'channel-623',
        'noble-1': 'channel-536',
        'stafihub-1': 'channel-369',
        'arkh': 'channel-253',
    },
    explorer: {
        address: 'https://ping.pub/cosmos/account/{}',
        tx: 'https://ping.pub/cosmos/tx/{}',
        validator: 'https://ping.pub/cosmos/staking/{}',
        block: 'https://ping.pub/cosmos/block/{}',
    },
    tokens: [
        {
            token: 'uatom',
            symbol: 'ATOM',
            name: 'Cosmos',
            icon: process.env.CF_PAGES_URL + '/img/coins/Cosmos.svg',
            decimals: 6,
            coinGeckoID: 'cosmos',
        },
    ],
}
