module.exports = {
  chainID: 'gravity-bridge-3',
  lcd: 'https://gravitychain.io:1317',
  rpc: 'https://gravitychain.io:26657',
  gasAdjustment: 1.75,
  gasPrices: { ugraviton: 0.0 },
  prefix: 'gravity',
  coinType: '118',
  baseAsset: 'ugraviton',
  name: 'Gravity Bridge',
  chainRegistryName: 'gravitybridge',
  disabledModules: ['swap'],
  icon: process.env.CF_PAGES_URL + '/img/chains/Gravity.svg',
  gitRepo: 'https://github.com/Gravity-Bridge/Gravity-Bridge',
  autoCompound: {
    enabled: true,
    minRewards: 1000000,
  },
  explorer: {
    address: 'https://ping.pub/gravity-bridge/account/{}',
    tx: 'https://ping.pub/gravity-bridge/tx/{}',
    validator: 'https://ping.pub/gravity-bridge/staking/{}',
    block: 'https://ping.pub/gravity-bridge/block/{}',
  },
  tokens: [
    {
      token: 'ugraviton',
      symbol: 'GRAV',
      name: 'Gravity Bridge',
      icon: process.env.CF_PAGES_URL + '/img/coins/Gravity.svg',
      decimals: 6,
      coinGeckoID: 'graviton',
    },
    {
      token: 'gravity0xfB5c6815cA3AC72Ce9F5006869AE67f18bF77006',
      symbol: 'PSTAKE',
      name: 'PSTAKE Finance',
      icon:
        process.env.CF_PAGES_URL +
        '/img/coins/gravity0xfB5c6815cA3AC72Ce9F5006869AE67f18bF77006.png',
      decimals: 18,
      coinGeckoID: 'pstake-finance',
    },
    {
      token: 'gravity0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
      symbol: 'WETH',
      name: 'WETH',
      icon: process.env.CF_PAGES_URL + '/img/coins/Gravity.svg',
      decimals: 18,
    },
    {
      token: 'gravity0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
      symbol: 'USDC',
      name: 'USDC',
      icon: process.env.CF_PAGES_URL + '/img/coins/USDC.svg',
      decimals: 6,
      coinGeckoID: 'usd-coin',
    },
    {
      token: 'gravity0xdAC17F958D2ee523a2206206994597C13D831ec7',
      symbol: 'USDT',
      name: 'USDT',
      icon: process.env.CF_PAGES_URL + '/img/coins/USDT.svg',
      decimals: 6,
      coinGeckoID: 'tether',
    },
  ],
}
