module.exports = {
    chainID: 'injective-1',
    lcd: 'https://injective-rest.publicnode.com',
    rpc: 'https://injective-rpc.publicnode.com',
    gasAdjustment: 1.75,
    gasPrices: {inj: 1000000000},
    prefix: 'inj',
    coinType: '60',
    baseAsset: 'inj',
    name: 'Injective',
    chainRegistryName: 'injective',
    disabledModules: ['swap'],
    icon: process.env.CF_PAGES_URL + '/img/chains/Injective.svg',
    gitRepo: 'https://github.com/injectivefoundation/injective-core',
    autoCompound: {
        enabled: true,
        minRewards: 100000000000000000
    },
    channels: {
        'phoenix-1': 'channel-151',
        'axelar-dojo-1': 'channel-84',
        'cosmoshub-4': 'channel-1',
        'crescent-1': 'channel-90',
        'migaloo-1': 'channel-102',
        'osmosis-1': 'channel-8',
        'stride-1': 'channel-89',
        'kaiyo-1': 'channel-98',
    },
    explorer: {
        address: 'https://ping.pub/injective/account/{}',
        tx: 'https://ping.pub/injective/tx/{}',
        validator: 'https://ping.pub/injective/staking/{}',
        block: 'https://ping.pub/injective/block/{}',
    },
    tokens: [
        {
            token: 'inj',
            symbol: 'INJ',
            name: 'Injective',
            icon: process.env.CF_PAGES_URL + '/img/coins/Injective.svg',
            decimals: 18,
            coinGeckoID: 'injective-protocol',
        },
    ],
    cw20Tokens: require('../../cw20/tokens/mainnet/injective'),
}
