module.exports = {
    chainID: 'juno-1',
    lcd: 'https://juno-rest.publicnode.com',
    rpc: 'https://juno-rpc.publicnode.com',
    gasAdjustment: 1.75,
    gasPrices: {ujuno: 0.1},
    prefix: 'juno',
    coinType: '118',
    baseAsset: 'ujuno',
    name: 'Juno',
    chainRegistryName: 'juno',
    disabledModules: ['swap'],
    icon: process.env.CF_PAGES_URL + '/img/chains/Juno.svg',
    gitRepo: 'https://github.com/CosmosContracts/juno',
    autoCompound: {
        enabled: true,
        minRewards: 100000
    },
    ibc: {
        fromTerra: 'channel-20',
        toTerra: 'channel-27',
    },
    channels: {
        'columbus-5': 'channel-27',
        'phoenix-1': 'channel-86',
        'axelar-dojo-1': 'channel-71',
        'akashnet-2': 'channel-29',
        'chihuahua-1': 'channel-28',
        'comdex-1': 'channel-36',
        'cosmoshub-4': 'channel-1',
        'crescent-1': 'channel-81',
        'osmosis-1': 'channel-0',
        'stride-1': 'channel-139',
        'archway-1': 'channel-290',
        'noble-1': 'channel-224',
    },
    explorer: {
        address: 'https://ping.pub/juno/account/{}',
        tx: 'https://ping.pub/juno/tx/{}',
        validator: 'https://ping.pub/juno/staking/{}',
        block: 'https://ping.pub/juno/block/{}',
    },
    tokens: [
        {
            token: 'ujuno',
            symbol: 'JUNO',
            name: 'Juno',
            icon: process.env.CF_PAGES_URL + '/img/coins/Juno.svg',
            decimals: 6,
            coinGeckoID: 'juno-network',
        },
    ],
    cw20Tokens: require('../../cw20/tokens/mainnet/juno'),
}
