module.exports = {
    chainID: 'neutron-1',
    lcd: 'https://neutron-rest.publicnode.com',
    rpc: 'https://neutron-rpc.publicnode.com',
    gasAdjustment: 1.75,
    gasPrices: {
        untrn: 0.84,
        'ibc/C4CFF46FD6DE35CA4CF4CE031E643C8FDC9BA4B99AE598E9B0ED98FE3A2319F9': 0.03,
        'ibc/F082B65C88E4B6D5EF1DB243CDA1D331D002759E938A0F5CD3FFDC5D53B3E349': 0.3,
    },
    prefix: 'neutron',
    coinType: '118',
    baseAsset: 'untrn',
    name: 'Neutron',
    chainRegistryName: 'neutron',
    disabledModules: ['staking', 'gov', 'swap'],
    icon: process.env.CF_PAGES_URL + '/img/chains/Neutron.png',
    gitRepo: 'https://github.com/neutron-org/neutron',
    autoCompound: {
        enabled: true,
        minRewards: 1000000
    },
    channels: {
        'osmosis-1': 'channel-10',
        'stride-1': 'channel-8',
        'axelar-dojo-1': 'channel-2',
        'cosmoshub-4': 'channel-1',
        'mars-1': 'channel-16',
        'kaiyo-1': 'channel-3',
        'phoenix-1': 'channel-25',
        'stargaze-1': 'channel-18',
    },
    icsChannels: {},
    explorer: {
        address: 'https://ping.pub/neutron/account/{}',
        tx: 'https://ping.pub/neutron/tx/{}',
        validator: 'https://ping.pub/neutron/staking/{}',
        block: 'https://ping.pub/neutron/block/{}',
    },
    tokens: [
        {
            token: 'untrn',
            symbol: 'NTRN',
            name: 'Neutron',
            icon: process.env.CF_PAGES_URL + '/img/coins/Neutron.png',
            decimals: 6,
            coinGeckoID: 'neutron-3',
        },
        {
            token: 'uatom',
            symbol: 'ATOM',
            name: 'Cosmos',
            icon: process.env.CF_PAGES_URL + '/img/coins/Cosmos.svg',
            decimals: 6,
        },
        {
            token: 'uusdc',
            symbol: 'USDC',
            name: 'usdc',
            icon: process.env.CF_PAGES_URL + '/img/coins/axlUSDC.svg',
            decimals: 6,
        },
    ],
    cw20Tokens: require('../../cw20/tokens/mainnet/neutron'),
}
